name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: square-middleware-prod-api
  AZURE_FUNCTIONAPP_NAME: square-middleware-functions
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '20.x'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false

      - name: Install Azure Functions Core Tools
        run: npm install -g azure-functions-core-tools@4 --unsafe-perm true

      - name: Install production dependencies
        run: npm ci --omit=dev

      - name: Create deployment package
        run: |
          rm -rf deploy
          mkdir -p deploy
          cp -R src deploy/
          cp package.json package-lock.json deploy/
          cp -R node_modules deploy/

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ./deploy

      - name: Configure Health Check
        run: |
          echo "Configuring health check path..."
          az resource update \
            --resource-group square-middleware-prod-rg \
            --resource-type Microsoft.Web/sites \
            --name "${{ env.AZURE_WEBAPP_NAME }}/config/web" \
            --set properties.healthCheckPath="/api/health"

      - name: Install Function App dependencies
        working-directory: azure-functions
        run: |
          rm -rf node_modules
          npm ci --omit=dev

      - name: Deploy Azure Functions
        working-directory: azure-functions
        run: func azure functionapp publish ${{ env.AZURE_FUNCTIONAPP_NAME }} --node

      - name: Azure Logout
        if: always()
        run: az logout
