name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: square-middleware-prod-api
  AZURE_WEBAPP_PACKAGE_PATH: "."
  NODE_VERSION: "20.x"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false

      - name: Create deployment package
        run: |
          mkdir -p deploy
          cp -r src/* deploy/
          cp package.json package-lock.json deploy/

      - name: Install production dependencies
        run: |
          cd deploy
          npm ci --omit=dev

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ./deploy

      - name: Configure Health Check
        run: |
          echo "Configuring health check path..."
          az resource update \
            --resource-group square-middleware-prod-rg \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-type "Microsoft.Web/sites/config" \
            --parent "sites/${{ env.AZURE_WEBAPP_NAME }}" \
            --set properties.healthCheckPath="/api/health" \
            --api-version 2022-03-01

      - name: Azure Logout
        if: always()
        run: az logout
