name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: square-middleware-prod-api
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '20.x'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false

      - name: Deploy to Azure Web App
        run: |
          # Stop the app temporarily to prevent deployment conflicts
          echo "Stopping app to prevent deployment conflicts..."
          az webapp stop \
            --resource-group square-middleware-prod-rg \
            --name ${{ env.AZURE_WEBAPP_NAME }} || echo "App already stopped"

          # Create a clean deployment directory
          mkdir -p deploy

          # Copy ONLY source code and package files (Azure will install node_modules)
          cp -r src package.json package-lock.json deploy/

          # Create deployment package WITHOUT node_modules
          cd deploy
          zip -r ../deployment.zip .
          cd ..

          echo "Deploying to Web App: ${{ env.AZURE_WEBAPP_NAME }}"

          # Deploy to Azure Web App using the new command
          az webapp deploy \
            --resource-group square-middleware-prod-rg \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --src-path deployment.zip \
            --type zip \
            --async false \
            --clean true \
            --restart true

      - name: Configure Health Check
        run: |
          echo "Configuring health check path..."
          az webapp config set \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group square-middleware-prod-rg \
            --health-check-path /api/health

      - name: Azure Logout
        if: always()
        run: az logout
